export const CartActionTypes = {
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  DECREASE_ITEM_QTY: 'DECREASE_ITEM_QTY',
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN'
};

export const UserActionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER'
};

export const ShopActionTypes = {
  UPDATE_COLLECTIONS: 'UPDATE_COLLECTIONS'
};
